version: '3.8'

services:
  # CockroachDB - Production Database
  cockroachdb:
    image: cockroachdb/cockroach:v23.1.15
    container_name: voltedge-cockroachdb-prod
    command: start-single-node --insecure --http-addr=0.0.0.0:8080 --listen-addr=0.0.0.0:26257
    ports:
      - "26257:26257"  # SQL port
      - "8081:8080"    # Admin UI port
    volumes:
      - cockroach_data_prod:/cockroach/cockroach-data
      - ./database/init:/docker-entrypoint-initdb.d
    environment:
      - COCKROACH_DATABASE=voltedge
      - COCKROACH_USER=voltedge
      - COCKROACH_PASSWORD=${DB_PASSWORD:-voltedge_secure_password}
    healthcheck:
      test: ["CMD", "cockroach", "node", "status", "--insecure"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - voltedge-network
    restart: unless-stopped

  # Zig Simulation Engine
  zig-core:
    build:
      context: ./zig-core
      dockerfile: Dockerfile.simple
    ports:
      - "9091:9091"  # gRPC port
    environment:
      - SIMULATION_MODE=production
      - LOG_LEVEL=info
      - MAX_SIMULATIONS=100
    volumes:
      - ./data/simulations:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9091"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - voltedge-network

  # Go API Gateway
  api-gateway:
    build:
      context: ./go-services
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # HTTP API
      - "8082:8081"  # WebSocket
      - "9090:9090"  # Metrics
    environment:
      - ZIG_GRPC_ENDPOINT=zig-core:9091
      - DATABASE_URL=postgres://voltedge:${DB_PASSWORD:-voltedge_secure_password}@cockroachdb:26257/voltedge?sslmode=disable
      - LOG_LEVEL=info
      - METRICS_ENABLED=true
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_here}
    depends_on:
      zig-core:
        condition: service_healthy
      cockroachdb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - voltedge-network

  # Svelte Frontend
  frontend:
    build:
      context: ./svelte-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=${API_URL:-http://localhost:8080}
      - VITE_WS_URL=${WS_URL:-ws://localhost:8081}
      - VITE_APP_VERSION=${APP_VERSION:-1.0.0}
    depends_on:
      api-gateway:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - voltedge-network

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9092:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data_prod:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=30d'
    restart: unless-stopped
    networks:
      - voltedge-network

  # Grafana for dashboards
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_DISABLE_GRAVATAR=true
    volumes:
      - grafana_data_prod:/var/lib/grafana
      - ./docker/grafana:/etc/grafana/provisioning
    restart: unless-stopped
    networks:
      - voltedge-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - api-gateway
    restart: unless-stopped
    networks:
      - voltedge-network

volumes:
  prometheus_data_prod:
  grafana_data_prod:
  cockroach_data_prod:

networks:
  voltedge-network:
    driver: bridge